# Generated by Django 4.2.3 on 2023-08-29 20:01

import base.validators
from django.db import migrations
import imagekit.models.fields
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar.svg', upload_to=users_app.models.user_avatar_path, validators=[base.validators.FileValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'ico', 'svg'], allowed_mimetypes=['image/jpeg', 'image/x-png', 'image/png', 'image/webp', 'image/x-icon', 'image/svg+xml'], max_size=5242880, min_size=0)]),
        ),
    ]
