# Generated by Django 4.2.3 on 2023-09-25 15:07

import base.validators
from django.db import migrations
import gallery.utils
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=gallery.utils.user_avatar_path, validators=[base.validators.FileValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'ico', 'svg'], allowed_mimetypes=['image/jpeg', 'image/x-png', 'image/png', 'image/webp', 'image/x-icon', 'image/svg+xml'], max_size=5242880, min_size=0)]),
        ),
    ]
