# Generated by Django 4.2.3 on 2023-07-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
