# Generated by Django 4.2.3 on 2023-07-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_imageroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
