# Generated by Django 4.2.3 on 2023-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_imageroom_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageroom',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='imageroom',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageroom',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageroom',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images/', width_field='width'),
        ),
    ]
