# Generated by Django 4.2.3 on 2023-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_name_alter_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_changed',
            field=models.BooleanField(default=False),
        ),
    ]
