# Generated by Django 4.2.3 on 2023-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_imagemodel_image_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_created',
            field=models.BooleanField(default=False),
        ),
    ]
