# Generated by Django 4.2.3 on 2023-08-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_imagemodel_image_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image_changed',
            new_name='image_flag',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_created',
        ),
    ]
