# Generated by Django 4.2.3 on 2023-08-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_country_alter_user_adress_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_flag',
        ),
    ]
