# Generated by Django 4.2.3 on 2023-10-19 06:46

import base.validators
from django.db import migrations, models
import gallery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=gallery.utils.user_directory_path, validators=[base.validators.FileValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'ico'], allowed_mimetypes=['image/jpeg', 'image/x-png', 'image/png', 'image/webp', 'image/x-icon'], max_size=12582912)])),
                ('is_private', models.BooleanField(default=False)),
                ('image_views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
