# Generated by Django 4.2.3 on 2023-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='unique_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
