# Generated by Django 4.2.3 on 2023-08-09 05:47

import base.models
import base.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=base.models.user_directory_path, validators=[base.validators.FileValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'ico'], allowed_mimetypes=['image/jpeg', 'image/x-png', 'image/png', 'image/webp', 'image/x-icon'], max_size=15728640)]),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tag'),
        ),
    ]
