# Generated by Django 4.2.3 on 2023-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_imagemodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_views',
            field=models.IntegerField(default=0),
        ),
    ]
